pygments: true
main_title: Sarawak Report Election Bribe Watch
include: [a, c, j]
auto: true
navigation:
- text: See Bribes
  url: index.html
  idd: view
- text: Add Bribe
  url: submit.html
  idd: submit