pygments: true
main_title: Sarawak Report Election Bribe Watch
include: [a, c, j]
auto: true
navigation:
- text: Map
  url: index.html
  idd: view
- text: Submit Bribe
  url: submit.html
  idd: submit
- text: Get in touch
  url: touch.html
  idd: touch